### ISSUE TITLE
Error in Omnis Studio 5.0.1

### ISSUE THREAD

**Issue by Andrec74** [graemereid/JSON_for_Studio5#1]
Hi, I tried to open the library with Omnis Studio 5.0.1 Dev but the library is not opened. Is it possible that it is not compatible with my version?

Thanks

**Comment by graemereid** [comment]
[JSON_FOR_STUDIO5.zip](https://github.com/graemereid/JSON_for_Studio5/files/1715203/JSON_FOR_STUDIO5.zip)

Andre,

Sorry about that. The library was actually developed/saved using Omnis Studio 5.2.3.1. I have created a new library using Studio 5.0, and transferred the code across. Can you try the attached library and let me know if that works for you? If so, I will work out the best way to include it in the GitHub repository.

Regards,
Graeme

**Comment by Andrec74** [comment]
Graeme,
thank you it works great also with version 5.0.1. Great work was what I needed.

Regards,
Andrea

**Comment by graemereid** [comment]
Rebuild the library using Studio 5.0 so it will work with older versions of Studio 5. Opening this library with later versions (eg Studio 5.2.3.1) should automatically convert the library.
